<a href="https://colab.research.google.com/github/yousseflashin/DeepLearing_start/blob/main/Start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Settin numby

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:

#define array of np's
my_array=np.array([10,20,30,40])
print(my_array)
print(type(my_array))
print(my_array.shape)
print(my_array[1])
my_array[3]=55
print( *(value for value in my_array) )
print(my_array[0:3]) #from 0 to 2 not taking the 3 index

In [ ]:

my_array=np.array([[10,20,30,40],[50,60,70,80]])
print(my_array)
print(type(my_array))
print(my_array.shape)
print(my_array[1])
print(my_array[0:1,1:2])
my_array[1][3]=55
for value in my_array:
  print(value)
  for mvalue in value:
    print(mvalue)


In [35]:
All_zero_array=np.zeros((3,3))
print(All_zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
All_one_array=np.ones((3,3))
print(All_one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
idesntity_type_array=np.eye((3))# spacify only the the number of one because this type of aray are square form
print(idesntity_type_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
constant_type_array=np.full((4,4),7)
print(constant_type_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [40]:
random_array_type=np.random.random((3,3))
print(random_array_type)

[[0.64297006 0.88700662 0.2964551 ]
 [0.30285714 0.14029063 0.63939674]
 [0.5586696  0.67372455 0.34240144]]
